// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo9FXklTOEyj7nThIN3zGbtgEtlUsssXg',
    appId: '1:314668425909:web:aa0e7314fdc7f927b814fc',
    messagingSenderId: '314668425909',
    projectId: 'yakittakip-27877',
    authDomain: 'yakittakip-27877.firebaseapp.com',
    storageBucket: 'yakittakip-27877.firebasestorage.app',
    measurementId: 'G-58KBCH9E68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-6GCvUXuEJzU_HMs3snTNRiJF9RT7O80',
    appId: '1:314668425909:android:2dec2f4dadb769fab814fc',
    messagingSenderId: '314668425909',
    projectId: 'yakittakip-27877',
    storageBucket: 'yakittakip-27877.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSWbjN_BGrY1RY-h9IceOt5psJTZO_OUc',
    appId: '1:314668425909:ios:0b97f8c2054eab9bb814fc',
    messagingSenderId: '314668425909',
    projectId: 'yakittakip-27877',
    storageBucket: 'yakittakip-27877.firebasestorage.app',
    iosBundleId: 'com.yakittakip.app',
  );
}
